version: "3.4"
services:
  # Postgres DB
  db:
    image: postgres:12
    tmpfs: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api:
    image: eclanp/graphjin:latest
    environment:
      GO_ENV: "development"
    volumes:
      - ./config:/config
      - ./keys:/keys/
    ports:
      - "8080:8080"
    depends_on:
      - db
